<GridLayout2>:
    cols: 2
    spacing: 10
    padding: 10

    Button:
        text: "one"
    Button:
        text: "two"
    Button:
        text: "three"
    Button:
        text: "four"
    Button:
        text: "five"
    Button:
        text: "six"
    AsyncImage:
        source: 'https://upload.wikimedia.org/wikipedia/commons/6/6f/180328_Sunmi_perfoming_at_Keimyung_University_%289%29_%28cropped%29.jpg'

